// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: pinger.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - pinger.Pinger

/// Namespace containing generated types for the "pinger.Pinger" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Pinger_Pinger {
    /// Service descriptor for the "pinger.Pinger" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "pinger.Pinger")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Ping" metadata.
        public enum Ping {
            /// Request type for "Ping".
            public typealias Input = Pinger_Empty
            /// Response type for "Ping".
            public typealias Output = Pinger_Pong
            /// Descriptor for "Ping".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "pinger.Pinger"),
                method: "Ping"
            )
        }
        /// Descriptors for all methods in the "pinger.Pinger" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Ping.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "pinger.Pinger" service.
    public static let pinger_Pinger = GRPCCore.ServiceDescriptor(fullyQualifiedService: "pinger.Pinger")
}

// MARK: pinger.Pinger (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Pinger_Pinger {
    /// Streaming variant of the service protocol for the "pinger.Pinger" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Ping" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Pinger_Empty` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Pinger_Pong` messages.
        func ping(
            request: GRPCCore.StreamingServerRequest<Pinger_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Pinger_Pong>
    }

    /// Service protocol for the "pinger.Pinger" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Pinger_Pinger.StreamingServiceProtocol {
        /// Handle the "Ping" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Pinger_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Pinger_Pong` message.
        func ping(
            request: GRPCCore.ServerRequest<Pinger_Empty>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Pinger_Pong>
    }

    /// Simple service protocol for the "pinger.Pinger" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Pinger_Pinger.ServiceProtocol {
        /// Handle the "Ping" method.
        ///
        /// - Parameters:
        ///   - request: A `Pinger_Empty` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Pinger_Pong` to respond with.
        func ping(
            request: Pinger_Empty,
            context: GRPCCore.ServerContext
        ) async throws -> Pinger_Pong
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Pinger_Pinger.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Pinger_Pinger.Method.Ping.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Pinger_Empty>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Pinger_Pong>(),
            handler: { request, context in
                try await self.ping(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Pinger_Pinger.ServiceProtocol {
    public func ping(
        request: GRPCCore.StreamingServerRequest<Pinger_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Pinger_Pong> {
        let response = try await self.ping(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Pinger_Pinger.SimpleServiceProtocol {
    public func ping(
        request: GRPCCore.ServerRequest<Pinger_Empty>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Pinger_Pong> {
        return GRPCCore.ServerResponse<Pinger_Pong>(
            message: try await self.ping(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: pinger.Pinger (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Pinger_Pinger {
    /// Generated client protocol for the "pinger.Pinger" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Ping" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Pinger_Empty` message.
        ///   - serializer: A serializer for `Pinger_Empty` messages.
        ///   - deserializer: A deserializer for `Pinger_Pong` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func ping<Result>(
            request: GRPCCore.ClientRequest<Pinger_Empty>,
            serializer: some GRPCCore.MessageSerializer<Pinger_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Pinger_Pong>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Pinger_Pong>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "pinger.Pinger" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Ping" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Pinger_Empty` message.
        ///   - serializer: A serializer for `Pinger_Empty` messages.
        ///   - deserializer: A deserializer for `Pinger_Pong` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func ping<Result>(
            request: GRPCCore.ClientRequest<Pinger_Empty>,
            serializer: some GRPCCore.MessageSerializer<Pinger_Empty>,
            deserializer: some GRPCCore.MessageDeserializer<Pinger_Pong>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Pinger_Pong>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Pinger_Pinger.Method.Ping.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Pinger_Pinger.ClientProtocol {
    /// Call the "Ping" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Pinger_Empty` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func ping<Result>(
        request: GRPCCore.ClientRequest<Pinger_Empty>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Pinger_Pong>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.ping(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Pinger_Empty>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Pinger_Pong>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Pinger_Pinger.ClientProtocol {
    /// Call the "Ping" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func ping<Result>(
        _ message: Pinger_Empty,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Pinger_Pong>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Pinger_Empty>(
            message: message,
            metadata: metadata
        )
        return try await self.ping(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}
