// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pinger.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pinger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pinger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pinger_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_pinger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_pinger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_pinger_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_pinger_proto protoreflect.FileDescriptor

const file_pinger_proto_rawDesc = "" +
	"\n" +
	"\fpinger.proto\x12\x06pinger\"\a\n" +
	"\x05Empty\"\x1a\n" +
	"\x04Pong\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2/\n" +
	"\x06Pinger\x12%\n" +
	"\x04Ping\x12\r.pinger.Empty\x1a\f.pinger.Pong\"\x00B\x19Z\x17swift_grpc/server/protob\x06proto3"

var (
	file_pinger_proto_rawDescOnce sync.Once
	file_pinger_proto_rawDescData []byte
)

func file_pinger_proto_rawDescGZIP() []byte {
	file_pinger_proto_rawDescOnce.Do(func() {
		file_pinger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pinger_proto_rawDesc), len(file_pinger_proto_rawDesc)))
	})
	return file_pinger_proto_rawDescData
}

var file_pinger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pinger_proto_goTypes = []any{
	(*Empty)(nil), // 0: pinger.Empty
	(*Pong)(nil),  // 1: pinger.Pong
}
var file_pinger_proto_depIdxs = []int32{
	0, // 0: pinger.Pinger.Ping:input_type -> pinger.Empty
	1, // 1: pinger.Pinger.Ping:output_type -> pinger.Pong
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pinger_proto_init() }
func file_pinger_proto_init() {
	if File_pinger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pinger_proto_rawDesc), len(file_pinger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pinger_proto_goTypes,
		DependencyIndexes: file_pinger_proto_depIdxs,
		MessageInfos:      file_pinger_proto_msgTypes,
	}.Build()
	File_pinger_proto = out.File
	file_pinger_proto_goTypes = nil
	file_pinger_proto_depIdxs = nil
}
